---
name: Demo App2
description: >
  DUN DIN 
version: 0.0.1-rancher1
category: Toy Apps
maintainer: Nathan Valentine <nathan@rancher.com|nrvale0@gmail.com>
license: Apache2
projectURL: https://github.com/eagledrone/cattle/
